accounts/urls.py
from django.urls import path
from . import views
# app_name은 왜 쓸까요?
# 우리는 기본적으로 URL을 모두 변수화해서 쓰고 있음
# Template, View에서 직접 '/accounts/' X 
# app_name과 path 이름으로 

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
# URL설정을 app 단위로!
from django.urls import path 
from . import views

app_name = 'articles'

urlpatterns = [
  path('', views.index, name='index'),
  path('create/', views.create, name='create'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/comments/', views.comment_create, name='comment_create'),
  path('<int:pk>/likes/', views.likes, name='likes'),
  
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

articles/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models

# Create your models here.
'''
게시판 기능 
- 제목(20글자이내)
- 내용(긴 글)
- 글 작성시간/수정시간(자동으로 기록, 날짜/시간)
'''
# 1. 모델 설계 (DB 스키마 설계)
from django.conf import settings

class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(1200, 960)],
                                format='JPEG',
                                options={'quality': 80})
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    
class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('username', )

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email',)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserChangeForm, CustomUserCreationForm

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save() 
            auth_login(request, user)  
            return redirect('articles:index')
    else:   
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)
@require_safe
def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        'user': user
    }
    return render(request, 'accounts/detail.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    messages.warning(request, '로그아웃 하였습니다.')
    return redirect('articles:index')

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:detail', request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

@require_POST
def follow(request,pk):
    if request.user.is_authenticated:
        fuser = get_object_or_404(get_user_model(), pk=pk)
        if request.user == fuser:
            messages.warning(request,'자기자신 팔로우 불가')
            return redirect('accounts:detail', pk)
        if request.user in fuser.followers.all():
            fuser.followers.remove(request.user)
        else:
            fuser.followers.add(request.user)
        return redirect('accounts:detail',pk)
    return redirect('accounts:login')

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <h1>{{ user.username }}님의 프로필</h1>
  {% if request.user.is_authenticated %}
    {% if request.user != fuser %}
      <form action="{% url 'accounts:follow' user.pk%}" method='POST'>
        {% csrf_token %}
        {% if request.user in user.followers.all %}
          <input type="submit" value='unfollow' class='btn btn-outline-danger'>
        {% else %}
          <input type="submit" value='follow' class='btn btn-outline-primary'>
        {% endif %}
      </form>
    {% endif %}
  {% endif %}
  {% comment %} <button id='#follow'>follow</button>
  <script>
    const btn_follow = document.querySelector('#follow')
    btn_follow.addEventListener('click',function(){
      const btn_unfollow = document.querySelector('button')
      btn_unfollow.classList.toggle('btn-danger')
    })
    const btn_following = document.querySelector('#unfollow')
    btn_follow.addEventListener('click',function(){
      const btn_follow = document.querySelector('button')
      btn_follow.classList.toggle('btn-primary')
    }) 실패...
  </script> {% endcomment %} 
  <p>{{ user.email }}
    |
    {{ user.full_name }}</p>
  <div class="">
    <div class="row">
      <div class="col-6">
        <h3>팔로워 목록</h3>
        <p class="text-muted">{{user.followers.all|length}}
          follower</p>
        {% for fu in user.followers.all %}
          <p>
            {{ forloop.counter }}
            <a href="{% url 'accounts:detail' fu.pk %}">
              {{ fu.username }}
            </a>
          </p>
        {% endfor %}
      </div>
      <div class="col-6">
        <h3>팔로잉 목록</h3>
        <p class="text-muted">{{user.followings.all|length}}
          followings</p>
        {% for fu in user.followings.all %}
          <p>
            {{ forloop.counter }}
            <a href="{% url 'accounts:detail' fu.pk %}">
              {{ fu.username }}
            </a>
          </p>
        {% endfor %}
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <h3>작성한 글</h3>
        <p class="text-muted">{{ user.article_set.count }}개를 작성하였습니다.</p>
        {% for article in user.article_set.all %}
          <p>
            {{ forloop.counter }}
            <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
          </p>
        {% endfor %}
      </div>
      <div class="col-6">
        <h3>작성한 댓글</h3>
        <p class="text-muted">{{ user.comment_set.count }}개를 작성하였습니다.</p>
        {% for comment in user.comment_set.all %}
          <p>
            {{ forloop.counter }}
            <a href="{% url 'articles:detail' comment.article_id %}">{{ comment.content }}</a>
          </p>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock body %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>로그인</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="OK" class="btn btn-primary btn-md">
  </form>
{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>회원가입</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="OK" class="btn btn-primary btn-md">
  </form>

{% endblock body %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>프로필 업데이트</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="OK" class="btn btn-primary btn-md">
  </form>
{% endblock body %}